// Generated by scripts/generate-decor-store-page-fragments.ts. Do not edit.
import type { DecorStorePageId } from "../../page-contracts";

type SecondaryPageId = Exclude<DecorStorePageId, "home">;

export const decorStoreSecondaryPageFragmentLoaders = {
  "shop-left": () => import("./shop-left.generated").then(({ default: fragment }) => fragment),
  "shop-none": () => import("./shop-none.generated").then(({ default: fragment }) => fragment),
  "shop-right": () => import("./shop-right.generated").then(({ default: fragment }) => fragment),
  "collection": () => import("./collection.generated").then(({ default: fragment }) => fragment),
  "product": () => import("./product.generated").then(({ default: fragment }) => fragment),
  "wishlist": () => import("./wishlist.generated").then(({ default: fragment }) => fragment),
  "cart": () => import("./cart.generated").then(({ default: fragment }) => fragment),
  "checkout": () => import("./checkout.generated").then(({ default: fragment }) => fragment),
  "account": () => import("./account.generated").then(({ default: fragment }) => fragment),
  "blog": () => import("./blog.generated").then(({ default: fragment }) => fragment),
  "article": () => import("./article.generated").then(({ default: fragment }) => fragment),
  "about": () => import("./about.generated").then(({ default: fragment }) => fragment),
  "faq": () => import("./faq.generated").then(({ default: fragment }) => fragment),
  "contact": () => import("./contact.generated").then(({ default: fragment }) => fragment),
} as const satisfies Record<SecondaryPageId, () => Promise<string>>;
