import {
  Archive,
  ArrowLeft,
  ArrowRight,
  Check,
  ChevronDown,
  ChevronRight,
  CreditCard,
  Eye,
  Headphones,
  Heart,
  Mail,
  MapPin,
  MessageCircle,
  MessageSquareMore,
  Minus,
  NotebookTabs,
  Package,
  PackageOpen,
  Phone,
  PhoneCall,
  Plus,
  RefreshCw,
  Repeat,
  Scissors,
  Search,
  Send,
  Share2,
  Shield,
  ShoppingBag,
  Smile,
  Star,
  Ticket,
  Truck,
  User,
  Wallet,
  X,
} from "@lucide/vue";
import type { fashionStoreBrandIcons } from "./brands";

export const fashionStoreUiIcons = {
  archive: Archive,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  check: Check,
  "chevron-down": ChevronDown,
  "chevron-right": ChevronRight,
  "credit-card": CreditCard,
  eye: Eye,
  headphones: Headphones,
  heart: Heart,
  mail: Mail,
  "map-pin": MapPin,
  "message-circle": MessageCircle,
  "message-square-more": MessageSquareMore,
  minus: Minus,
  "notebook-tabs": NotebookTabs,
  package: Package,
  "package-open": PackageOpen,
  phone: Phone,
  "phone-call": PhoneCall,
  plus: Plus,
  "refresh-cw": RefreshCw,
  repeat: Repeat,
  scissors: Scissors,
  search: Search,
  send: Send,
  "share-2": Share2,
  shield: Shield,
  "shopping-bag": ShoppingBag,
  smile: Smile,
  star: Star,
  ticket: Ticket,
  truck: Truck,
  user: User,
  wallet: Wallet,
  x: X,
} as const;

export type FashionStoreIconName =
  keyof typeof fashionStoreUiIcons | keyof typeof fashionStoreBrandIcons;
