export const decorSourceContract = {
  sources: {
    demoCss: "demos/decor-store/decor-store.css",
    html: "demo-decor-store.html",
    responsiveCss: "css/responsive.css",
    sharedCss: "css/style.css",
    sharedRuntime: "js/main.js",
  },
  font: {
    family: "Plus Jakarta Sans",
    hash: "cd8db90cd950e26bc8761f65d323588bd5cd112d326d6d322bc7c8ea86771215",
    source: "Crafto Google Fonts Plus Jakarta Sans v12 Latin variable binary",
    weightAxis: { maximum: 800, minimum: 200 },
  },
  regions: [
    "header",
    "hero",
    "categories",
    "product-tabs",
    "marquee",
    "collection",
    "clients",
    "journal",
    "services",
    "footer",
    "cookie-message",
    "sticky-elements",
    "scroll-progress",
  ],
  sourceRegions: [
    { id: "header", inventorySelector: "header", selector: ".decor-header" },
    { id: "hero", inventorySelector: "#decor-store-slider", selector: ".decor-hero" },
    { id: "categories", inventorySelector: "section:nth-of-type(2)", selector: ".decor-categories" },
    { id: "product-tabs", inventorySelector: "section:nth-of-type(3)", selector: ".decor-products" },
    { id: "marquee", inventorySelector: "section:nth-of-type(4)", selector: ".decor-marquee" },
    { id: "collection", inventorySelector: "section:nth-of-type(5)", selector: ".decor-collection" },
    { id: "clients", inventorySelector: "section:nth-of-type(6)", selector: ".decor-clients" },
    { id: "journal", inventorySelector: "section:nth-of-type(7)", selector: ".decor-journal" },
    { id: "services", inventorySelector: "section:nth-of-type(8)", selector: ".decor-services" },
    { id: "footer", inventorySelector: "footer", selector: ".decor-footer" },
    { id: "cookie-message", inventorySelector: ".cookie-message", selector: ".decor-cookie-message" },
    { id: "sticky-elements", inventorySelector: ".theme-demos", selector: ".decor-sticky-actions" },
    { id: "scroll-progress", inventorySelector: ".scroll-progress", selector: ".decor-scroll-progress" },
  ],
  header: {
    announcement: "Free Delivery on orders over £120. Don't miss discount.",
    announcementAction: "Shop now",
    brand: "decshop",
    brandAssetId: "decor.logo-black",
    navigation: ["Home", "Shop", "Collections", "Pages", "Blog", "Contact"],
    shopColumns: [
      {
        heading: "Furniture",
        items: [
          "Modern chair",
          "Luxurious sofa",
          "Sitting tables",
          "Century cabinet",
          "Wooden stool",
          "Dining tabl",
        ],
      },
      {
        heading: "Lighting",
        items: [
          "Table lamps",
          "Wall lights",
          "Ceiling lights",
          "Chandeliers",
          "Smart lights",
          "Outdoor lights",
        ],
      },
      {
        heading: "Decor",
        items: [
          "Home decor",
          "Kitchen decor",
          "Office decor",
          "Wooden mirrors",
          "Designer clocks",
          "Spiritual",
        ],
      },
      {
        heading: "Cabinetry",
        items: [
          "Wardrobes",
          "Shoe racks",
          "Movable",
          "Folding storage",
          "Wooden units",
          "Kids storage",
        ],
      },
      {
        heading: "Commercial",
        items: [
          "Hotel furniture",
          "Bar furniture",
          "School furniture",
          "Public furniture",
          "Office furniture",
          "Lab furniture",
        ],
      },
    ],
    shopBanners: ["decor.menu-banner-01", "decor.menu-banner-02"],
    collectionItems: [
      ["decor.menu-category-01", "Designer stool"],
      ["decor.menu-category-02", "Modern chair"],
      ["decor.menu-category-03", "Table lamp"],
      ["decor.menu-category-04", "Home decor"],
      ["decor.menu-category-05", "Ceramic pots"],
      ["decor.menu-category-06", "Wooden table"],
    ],
    collectionBanners: ["decor.menu-banner-03", "decor.menu-banner-04"],
    pageItems: ["About", "FAQs", "Wishlist", "Account", "Cart", "Checkout"],
    cart: {
      count: 2,
      items: [
        ["decor.product-01", "Table clock", "1 x $23.00"],
        ["decor.product-03", "Ceramic mug", "2 x $15.00"],
      ],
      subtotal: "$199.99",
    },
    language: {
      initial: "English",
      options: [
        ["English", "decor.flag-usa"],
        ["France", "decor.flag-france"],
        ["Russian", "decor.flag-russian"],
        ["Spain", "decor.flag-spain"],
      ],
      persistence: "session-only",
    },
  },
  productDetail: {
    actions: ["Compare", "Ask a question", "Share"],
    gallery: { autoplayMs: 0, count: 7, direction: "horizontal", lightbox: true, loop: false },
    reviewCount: 165,
    paymentAssets: [
      "decor.payment-visa",
      "decor.payment-mastercard",
      "decor.payment-american-express",
      "decor.payment-discover",
      "decor.payment-diners-club",
      "decor.payment-union-pay",
    ],
    tabs: ["Description", "Additional information", "Shipping and return", "Reviews (3)"],
    tags: ["Chair", "Modern", "Wooden"],
    product: {
      comparePrice: "$85.00",
      description:
        "Lorem ipsum is simply dummy text of the printing and typesetting industry lorem ipsum standard.",
      name: "Minimalist wooden chair",
      price: "$65.00",
      sku: "M492300",
      vendor: "Interio",
    },
  },
  hero: {
    autoplayMs: 9_000,
    interaction: {
      pauseOnFocus: false,
      pauseOnHover: false,
      stopAfterLoops: 0,
      stopAtSlide: 1,
      stopLoop: true,
      swipeThresholdPx: 75,
    },
    transition: {
      direction: "horizontal",
      durationMs: 300,
      easing: "ease-in-out",
      effect: "fade",
    },
    layerTimeline: {
      durationMs: 2_700,
      layers: [
        { delayMs: 500, durationMs: 300, easing: "power3.inOut", id: "accent" },
        { delayMs: 900, durationMs: 500, easing: "back.out", id: "shape" },
        { delayMs: 1_000, durationMs: 800, easing: "power3.inOut", id: "product" },
        { delayMs: 1_200, durationMs: 1_000, easing: "power3.inOut", id: "heading" },
        { delayMs: 1_500, durationMs: 1_000, easing: "power3.inOut", id: "price" },
        { delayMs: 1_700, durationMs: 1_000, easing: "power3.inOut", id: "action" },
        { delayMs: 2_000, durationMs: 1_000, easing: "power4.inOut", gatesInteraction: false, id: "auxiliary-1" },
        { delayMs: 2_200, durationMs: 1_000, easing: "power4.inOut", gatesInteraction: false, id: "auxiliary-2" },
        { delayMs: 2_600, durationMs: 1_000, easing: "power4.inOut", gatesInteraction: false, id: "auxiliary-3" },
        { delayMs: 2_600, durationMs: 1_000, easing: "power4.inOut", gatesInteraction: false, id: "auxiliary-4" },
      ],
    },
    slides: [
      {
        accentAssetId: "decor.slider-01-img-02",
        assetId: "decor.slider-01-img-01",
        backgroundColor: "#e5eff3",
        backgroundAssetId: "decor.slider-01-img-03",
        heading: "Corby sofas",
        price: "$199.00",
        thumbAssetId: "decor.slider-01-thumb",
      },
      {
        accentAssetId: "decor.slider-02-img-05",
        assetId: "decor.slider-02-img-04",
        backgroundColor: "#f9f1eb",
        backgroundAssetId: "decor.slider-02-img-06",
        heading: "Verona sofas",
        price: "$259.00",
        thumbAssetId: "decor.slider-02-thumb",
      },
      {
        accentAssetId: "decor.slider-03-img-08",
        assetId: "decor.slider-03-img-07",
        backgroundColor: "#e9fafb",
        backgroundAssetId: "decor.slider-03-img-09",
        heading: "Lewis sofas",
        price: "$259.00",
        thumbAssetId: "decor.slider-03-thumb",
      },
    ],
  },
  categories: {
    banners: [
      ["decor.main-banner-01", "Wooden classic table", "large"],
      ["decor.main-banner-02", "Pottery products", "small"],
      ["decor.main-banner-03", "Florence compact", "small"],
    ],
    featured: [
      ["decor.icon-01", "Lamp", "02"],
      ["decor.icon-03", "Stool", "03"],
      ["decor.icon-02", "Chair", "05"],
      ["decor.icon-10", "Cabinet", "03"],
      ["decor.icon-04", "Light", "08"],
      ["decor.icon-05", "Sofa", "04"],
    ],
  },
  shop: {
    categoryFilters: [
      ["Chairs", "22"],
      ["Decor", "28"],
      ["Furnitures", "36"],
      ["Lighting", "24"],
      ["Sofas", "26"],
      ["Stools", "33"],
      ["Mirrors", "22"],
    ],
    colorFilters: [
      ["Black", "#232323", "05"],
      ["Chestnut", "#8e412e", "24"],
      ["Brown", "#e0a699", "32"],
      ["Pastel pink", "#e0a699", "22"],
      ["Litchen green", "#9da693", "09"],
      ["Yellow", "#e7c06d", "06"],
    ],
    fabricFilters: [
      ["Polyolefin", "decor.product-01", "08"],
      ["Jute fabric", "decor.product-14", "03"],
      ["Crepe fabric", "decor.product-12", "20"],
      ["Wollen fabric", "decor.product-05", "08"],
    ],
    priceFilters: [
      ["Under $25", "08"],
      ["$25 to $50", "05"],
      ["$50 to $100", "25"],
      ["$100 to $200", "18"],
      ["$200 & Above", "36"],
    ],
    products: [
      ["decor.product-01", "Table clock", "$30.00", "$23.00", "New"],
      ["decor.product-14", "Wood stool", "", "$54.00", ""],
      ["decor.product-12", "Ceramic mug", "$20.00", "$15.00", "New"],
      ["decor.product-05", "Decorative plants", "$30.00", "$35.00", ""],
      ["decor.product-06", "Ceramic pot", "", "$23.00", ""],
      ["decor.product-13", "Ceramic plate", "$25.00", "$15.00", ""],
      ["decor.product-09", "Ceramic container", "", "$35.00", ""],
      ["decor.product-10", "Design wall clock", "", "$19.00", ""],
      ["decor.product-03", "Watch box", "", "$22.00", ""],
      ["decor.product-15", "Modern stool", "", "$19.00", ""],
      ["decor.product-14", "Nutcracker", "", "$28.00", ""],
      ["decor.product-12", "Decor lamp", "", "$12.00", ""],
    ],
    newArrivals: [
      ["decor.product-01", "Table clock", "$30.00", "$23.00", ""],
      ["decor.product-14", "Wood stool", "$50.00", "$43.00", ""],
      ["decor.product-10", "Wall clock", "$20.00", "$15.00", ""],
      ["decor.product-06", "Ceramic pot", "$15.00", "$10.00", ""],
      ["decor.product-09", "Ceramic jar", "$35.00", "$30.00", ""],
      ["decor.product-15", "Classic stool", "$20.00", "$15.00", ""],
    ],
    tags: [
      "furniture",
      "living room",
      "lamp",
      "modern",
      "wooden",
      "armchair",
      "dining room",
      "handmade",
    ],
    titleAssetId: "decor.title-bg",
  },
  bestSellers: [
    ["decor.product-01", "Table clock", "$30.00", "$23.00", ""],
    ["decor.product-14", "Wood stool", "", "$54.00", "New"],
    ["decor.product-12", "Ceramic mug", "$20.00", "$15.00", ""],
    ["decor.product-05", "Decorative plants", "$30.00", "$35.00", ""],
    ["decor.product-06", "Ceramic pot", "", "$23.00", "New"],
    ["decor.product-13", "Ceramic plate", "$25.00", "$15.00", ""],
    ["decor.product-09", "Ceramic container", "", "$35.00", ""],
    ["decor.product-10", "Design wall clock", "", "$19.00", "Hot"],
  ],
  newArrivals: [
    ["decor.product-15", "Ceramic pot", "", "$23.00", ""],
    ["decor.product-13", "Ceramic plate", "", "$15.00", ""],
    ["decor.product-09", "Ceramic container", "", "$35.00", "New"],
    ["decor.product-10", "Design wall clock", "", "$19.00", ""],
    ["decor.product-01", "Table clock", "", "$23.00", ""],
    ["decor.product-14", "Wood stool", "", "$54.00", "New"],
    ["decor.product-12", "Ceramic mug", "", "$15.00", ""],
    ["decor.product-05", "Decorative plants", "", "$35.00", ""],
  ],
  marquee: [
    "Pay with multiple credit cards",
    "Get offer up to 50% on modern furniture",
    "Free shipping for orders over $130",
  ],
  marqueeMotion: {
    allowTouchMove: false,
    autoplayDelayMs: 1,
    direction: "horizontal",
    durationMs: 8_000,
    effect: "slide",
  },
  collection: {
    bannerAssetId: "decor.banner-04",
    heading: "Lounge collection",
    interaction: {
      allowTouchMove: true,
      autoplayDelayMs: 3_000,
      direction: "horizontal",
      effect: "fade",
      transitionDurationMs: 300,
    },
    products: [
      ["decor.product-slider-01", "Wooden cabinet", "$50.00", "$23.00"],
      ["decor.product-slider-02", "Modern chair", "$40.00", "$18.00"],
      ["decor.product-slider-03", "Classic stools", "$56.00", "$24.00"],
    ],
  },
  clients: [
    "decor.client-01",
    "decor.client-02",
    "decor.client-03",
    "decor.client-04",
    "decor.client-05",
  ],
  clientMotion: {
    allowTouchMove: false,
    autoplayDelayMs: 0,
    breakpoints: { 576: 2, 768: 3, 992: 3, 1200: 4 },
    effect: "slide",
    pauseOnMouseEnter: false,
    slideDurationMs: 3_000,
  },
  revealGroups: [
    { delayMs: 100, direction: "x", distancePx: 50, durationMs: 600, easing: "easeOutQuad", id: "category-heading", staggerMs: 150, target: "self" },
    { delayMs: 100, direction: "x", distancePx: 50, durationMs: 600, easing: "easeOutQuad", id: "category-icons", staggerMs: 150, target: "children" },
    { delayMs: 150, direction: "x", distancePx: 50, durationMs: 600, easing: "easeOutQuad", id: "category-banners", staggerMs: 150, target: "children" },
    { delayMs: 100, direction: "y", distancePx: 50, durationMs: 600, easing: "easeOutQuad", id: "product-tabs", staggerMs: 150, target: "children" },
    { delayMs: 150, direction: "y", distancePx: 50, durationMs: 600, easing: "easeOutQuad", id: "product-grid", staggerMs: 150, target: "children" },
    { delayMs: 100, direction: "none", distancePx: 0, durationMs: 600, easing: "easeOutQuad", id: "marquee", staggerMs: 150, target: "self" },
    { delayMs: 150, direction: "x-negative", distancePx: 50, durationMs: 600, easing: "easeOutQuad", id: "collection-banner", staggerMs: 150, target: "self" },
    { delayMs: 150, direction: "x", distancePx: 50, durationMs: 600, easing: "easeOutQuad", id: "collection-product", staggerMs: 150, target: "self" },
    { delayMs: 100, direction: "none", distancePx: 0, durationMs: 600, easing: "easeOutQuad", id: "clients", staggerMs: 150, target: "self" },
    { delayMs: 0, direction: "y", distancePx: 50, durationMs: 600, easing: "easeOutQuad", id: "journal-heading", staggerMs: 150, target: "children" },
    { delayMs: 100, direction: "y", distancePx: 50, durationMs: 600, easing: "easeOutQuad", id: "journal-grid", staggerMs: 150, target: "children" },
    { delayMs: 100, direction: "x", distancePx: 50, durationMs: 600, easing: "easeOutQuad", id: "services", staggerMs: 150, target: "children" },
  ],
  journal: {
    eyebrow: "Designers ideas",
    heading: "The decor article",
    items: [
      [
        "decor.blog-07",
        "Decor",
        "08 August 2023",
        "The best influencers to follow for sartorial inspiration",
      ],
      [
        "decor.blog-08",
        "Design",
        "12 August 2023",
        "Everything you need to know about decor's big night out",
      ],
      [
        "decor.blog-04",
        "Decor",
        "20 August 2023",
        "All the best looks & moments from the met gala 2023",
      ],
      [
        "decor.blog-03",
        "Decor",
        "26 August 2023",
        "Find a colour palettes that reflects your passion",
      ],
    ],
  },
  services: [
    ["decor.icon-06", "Free shipping", "Free return & exchange"],
    ["decor.icon-07", "Store locator", "Find nearest store"],
    ["decor.icon-08", "Secure payment", "100% secure method"],
    ["decor.icon-09", "Online support", "24/7 support center"],
  ],
  footer: {
    body: "Lorem ipsum amet adipiscing elit to eiusmod ad tempor.",
    brand: "decshop",
    brandAssetId: "decor.logo-white",
    brandAsset2xId: "decor.logo-white-2x",
    columns: {
      Categories: ["Bed room", "Living room", "Lightning", "Fabrics sofa"],
      Information: ["About us", "Contact us", "FAQs", "Payment"],
      Account: ["My account", "Orders", "Checkout", "My wishlists"],
    },
    member: {
      body: "Get everything you need succeed!",
      heading: "Newsletter",
      placeholder: "Enter your email",
    },
    payments: [
      "decor.payment-icon-01",
      "decor.payment-icon-02",
      "decor.payment-icon-03",
      "decor.payment-icon-04",
    ],
    legal:
      "This site is protected by reCAPTCHA and the Google privacy policy and terms of service apply.",
    copyright: "© 2024 Crafto is Proudly Powered by ThemeZaa",
    support: ["Need support?", "+1 234 567 8910"],
    care: ["Customer care", "info@domain.com"],
  },
  interactions: {
    collection: [
      "previous",
      "next",
      "keyboard",
      "swipe",
      "autoplay",
      "visibility-pause",
      "reduced-motion",
    ],
    header: ["hover", "focus", "escape", "outside-click", "mobile-disclosure"],
    hero: ["previous", "next", "keyboard", "swipe", "autoplay", "visibility-pause", "reduced-motion"],
    overlays: ["search", "cart", "cookie-dismiss"],
    productTabs: ["click", "arrow-keys", "home", "end"],
  },
} as const;

export const decorSourceRegions = decorSourceContract.sourceRegions;
export const decorSourceRegionOrder = decorSourceRegions.map(({ id }) => id);
export type DecorSourceContract = typeof decorSourceContract;
