export const fashionSourceContract = {
  sources: {
    demoCss: "demos/fashion-store/fashion-store.css",
    html: "demo-fashion-store.html",
    responsiveCss: "css/responsive.css",
    sharedCss: "css/style.css",
    sharedRuntime: "js/main.js",
  },
  referencePages: [
    ["demo-fashion-store.html", "/"],
    ["demo-fashion-store-about.html", "/about"],
    ["demo-fashion-store-account.html", "/account"],
    ["demo-fashion-store-blog-single-creative.html", "/magazine/1"],
    ["demo-fashion-store-cart.html", "/cart"],
    ["demo-fashion-store-checkout.html", "/checkout"],
    ["demo-fashion-store-collection.html", "/collections/new-arrivals"],
    ["demo-fashion-store-contact.html", "/contact"],
    ["demo-fashion-store-faq.html", "/faq"],
    ["demo-fashion-store-magazine.html", "/magazine"],
    ["demo-fashion-store-no-sidebar.html", "/collections/all?layout=no-sidebar"],
    ["demo-fashion-store-right-sidebar.html", "/collections/all?layout=right-sidebar"],
    ["demo-fashion-store-shop.html", "/collections/all"],
    ["demo-fashion-store-single-product.html", "/products/textured-sweater"],
    ["demo-fashion-store-wishlist.html", "/wishlist"],
  ],
  cartPage: {
    heading: "Shopping cart",
    items: [
      {
        assetId: "fashion.product-01",
        color: "Pink",
        name: "Textured sweater",
        price: "$23.00",
        quantity: 1,
        slug: "textured-sweater",
        total: "$23.00",
      },
      {
        assetId: "fashion.product-10",
        color: "Brown",
        name: "Bermuda shorts",
        price: "$35.00",
        quantity: 2,
        slug: "bermuda-shorts",
        total: "$70.00",
      },
      {
        assetId: "fashion.product-06",
        color: "White",
        name: "Pocket sweatshirt",
        price: "$15.00",
        quantity: 1,
        slug: "pocket-sweatshirt",
        total: "$15.00",
      },
    ],
    shipping: ["Free shipping", "Flat: $12.00", "Local pickup"],
    subtotal: "$405.00",
    total: "$405.00",
  },
  checkoutPage: {
    heading: "Checkout",
    paymentMethods: ["Direct bank transfer", "Check payments", "Cash on delivery", "PayPal"],
    shippingMethods: ["Free shipping", "Flat: $12.00", "Local pickup"],
  },
  regions: [
    "header",
    "hero",
    "services",
    "categories",
    "best-sellers",
    "promotion",
    "collection",
    "brands",
    "featured-products",
    "promises",
    "magazine",
    "footer",
    "cookie-message",
    "sticky-elements",
    "scroll-progress",
  ],
  breakpoints: {
    desktop: 1_200,
    laptop: 992,
    tablet: 768,
    mobile: 576,
  },
  header: {
    announcement: "Enjoy FREE standard delivery on orders over $100.",
    announcementAction: "Shop now",
    brand: "Lifestyle",
    brandAssetId: "fashion.logo-black",
    brandAsset2xId: "fashion.logo-black-2x",
    navigation: ["Home", "Shop", "Collection", "Magazine", "Pages", "Contact"],
    destinations: {
      collection: "/collections/all",
      navigation: [
        "/",
        "/collections/all",
        "/collections/new-arrivals",
        "/magazine",
        "/about",
        "/contact",
      ],
      pages: {
        About: "/about",
        Account: "/account",
        Cart: "/cart",
        Checkout: "/checkout",
        Faq: "/faq",
        Wishlist: "/wishlist",
      },
      shop: {
        Accessories: "/collections/accessories",
        Divided: "/collections/divided",
        Kids: "/collections/kids",
        Men: "/collections/men",
        Women: "/collections/women",
      },
    },
    shopColumns: [
      {
        heading: "Men",
        items: ["Jeans", "Trousers", "Swimwear", "Casual shirts", "Rain jackets", "Loungewear"],
      },
      {
        heading: "Women",
        items: [
          "Dupattas",
          "Leggings",
          "Ethnic wear",
          "Kurtas & suits",
          "Western wear",
          "Dress materials",
        ],
      },
      {
        heading: "Kids",
        items: ["Dresses", "Jumpsuits", "Track pants", "Ethnic wear", "Value packs", "Loungewear"],
      },
      {
        heading: "Divided",
        items: ["Tops", "Dresses", "Shorts", "Swimwear", "Jeans", "Jackets"],
      },
      {
        heading: "Accessories",
        items: ["Shoes", "Scarves", "Watches", "Wristwear", "Backpacks", "Sunglasses"],
      },
    ],
    shopBanners: ["fashion.menu-banner-01", "fashion.menu-banner-02"],
    collectionItems: [
      ["fashion.menu-category-01", "Polo t-shirts"],
      ["fashion.menu-category-02", "Sunglasses"],
      ["fashion.menu-category-03", "Skinny blazer"],
      ["fashion.menu-category-04", "Casual shoes"],
      ["fashion.menu-category-05", "Winter jackets"],
      ["fashion.menu-category-06", "Men's shorts"],
    ],
    pageItems: ["About", "Faq", "Wishlist", "Account", "Cart", "Checkout"],
    cart: {
      count: 2,
      items: [
        ["fashion.product-01", "Ribbed tank", "1 x $23.00"],
        ["fashion.product-02", "Pleated dress", "2 x $15.00"],
      ],
      subtotal: "$199.99",
    },
  },
  collectionPage: [
    ["fashion.menu-category-01", "Polo t-shirts", "8 items"],
    ["fashion.menu-category-02", "Sunglasses", "9 items"],
    ["fashion.menu-category-03", "Skinny blazer", "8 items"],
    ["fashion.menu-category-04", "Casual shoes", "5 items"],
    ["fashion.menu-category-05", "Winter jackets", "7 items"],
    ["fashion.menu-category-06", "Men's shorts", "3 items"],
  ],
  hero: {
    options: {
      autoplayMs: 4_000,
      breakpointPx: 1_199,
      desktopDirection: "vertical",
      disableOnInteraction: false,
      effect: "slide",
      keyboard: true,
      loop: true,
      mobileDirection: "horizontal",
      parallaxPx: 500,
      progress: "numeric-line",
      speedMs: 1_000,
      touch: true,
    },
    slides: [
      {
        assetId: "fashion.slider-01",
        eyebrow: "Discount on selected collection!",
        heading: "Women's collection",
      },
      {
        assetId: "fashion.slider-02",
        eyebrow: "Discount on selected collection!",
        heading: "Men's collection",
      },
      {
        assetId: "fashion.slider-03",
        eyebrow: "Discount on selected collection!",
        heading: "Children's collection",
      },
    ],
  },
  fonts: {
    alt: {
      binary: "outfit-latin.woff2",
      family: "Outfit",
      hash: "92684e4acde79ef07758cd09380b7e01e9824d8b061eddeda046f78c166d7b12",
      weights: [300, 400, 500, 600, 700, 800, 900],
    },
    primary: {
      binary: "figtree-latin.woff2",
      family: "Figtree",
      hash: "8330490a01c60c196eae00b823de8102275aaa5862e7b76a7af21b8745338928",
      weights: [300, 400, 500, 600, 700, 800],
    },
  },
  services: [
    ["fashion.service-box", "Free shipping", "Free shipping on first order"],
    ["fashion.service-return", "15 days returns", "Moneyback guarantee"],
    ["fashion.service-payment", "Secure payment", "100% protected payment"],
    ["fashion.service-support", "Online support", "24/7 days a week support"],
  ],
  categories: [
    ["fashion.banner-01", "Women", "8 items", "/collections/women"],
    ["fashion.banner-02", "Men", "9 items", "/collections/men"],
    ["fashion.banner-03", "Accessories", "8 items", "/collections/accessories"],
    ["fashion.banner-04", "Kids", "8 items", "/collections/kids"],
  ],
  shop: {
    categoryFilters: [
      ["Jeans", "22"],
      ["Trousers", "28"],
      ["Swimwear", "36"],
      ["Casual shirts", "24"],
      ["Winter jackets", "26"],
      ["Leggings", "33"],
      ["Dupattas", "22"],
    ],
    colorFilters: [
      ["Black", "#232323", "05"],
      ["Blue", "#5881bf", "24"],
      ["Brown", "#9f684f", "32"],
      ["Green", "#87a968", "22"],
      ["Maroon", "#b14141", "09"],
      ["Orange", "#d9653e", "06"],
    ],
    newArrivals: [
      ["fashion.product-01", "Textured sweater", "$30.00", "$23.00"],
      ["fashion.product-02", "Traveller shirt", "$50.00", "$43.00"],
      ["fashion.product-03", "Crewneck tshirt", "$20.00", "$15.00"],
      ["fashion.product-04", "Skinny trousers", "$15.00", "$10.00"],
      ["fashion.product-05", "Sleeve sweater", "$35.00", "$30.00"],
      ["fashion.product-06", "Pocket white", "$20.00", "$15.00"],
    ],
    products: [
      ["fashion.product-01", "Textured sweater", "$200.00", "$189.00", "New"],
      ["fashion.product-02", "Traveller shirt", "$350.00", "$289.00", ""],
      ["fashion.product-03", "Crewneck sweatshirt", "$220.00", "$199.00", ""],
      ["fashion.product-04", "Skinny trousers", "$300.00", "$259.00", ""],
      ["fashion.product-05", "Sleeve sweater", "$250.00", "$239.00", ""],
      ["fashion.product-06", "Pocket sweatshirt", "$200.00", "$189.00", "Hot"],
      ["fashion.product-07", "Cotton sweater", "$150.00", "$129.00", ""],
      ["fashion.product-08", "Texture regular", "$170.00", "$120.00", ""],
      ["fashion.product-09", "Sequined dress", "$190.00", "$150.00", ""],
      ["fashion.product-10", "Bermuda shorts", "$120.00", "$100.00", ""],
      ["fashion.product-11", "Traveller shirt", "$300.00", "$259.00", ""],
      ["fashion.product-12", "Textured sweater", "$300.00", "$259.00", ""],
    ],
    sizeFilters: [
      ["S", "08"],
      ["M", "05"],
      ["L", "25"],
      ["XL", "18"],
      ["XXL", "36"],
    ],
    tags: [
      "Coats",
      "Cotton",
      "Dresses",
      "Jackets",
      "Polyester",
      "Printed",
      "Shirts",
      "Shorts",
      "Tops",
    ],
  },
  productDetail: {
    actions: ["Compare", "Ask a question", "Share"],
    gallery: {
      assetIds: [
        "fashion.product-01",
        "fashion.product-02",
        "fashion.product-03",
        "fashion.product-04",
        "fashion.product-05",
        "fashion.product-06",
      ],
      autoplayMs: 2_000,
      count: 6,
      direction: "vertical",
      lightbox: true,
      loop: true,
    },
    reviewCount: 165,
    paymentAssets: [
      "fashion.payment-visa",
      "fashion.payment-mastercard",
      "fashion.payment-american-express",
      "fashion.payment-discover",
      "fashion.payment-diners-club",
      "fashion.payment-union-pay",
    ],
    product: {
      category: "Woman",
      comparePrice: "$85.00",
      description:
        "Lorem ipsum is simply dummy text of the printing and typesetting industry lorem ipsum standard.",
      name: "Relaxed corduroy shirt",
      price: "$65.00",
      sku: "M492300",
      vendor: "Zalando",
    },
    tabs: ["Description", "Additional information", "Shipping and return", "Reviews (3)"],
    tags: ["Shirts", "Cotton", "Printed"],
  },
  bestSellers: [
    ["fashion.product-01", "Textured sweater", "$200.00", "$189.00", "New"],
    ["fashion.product-02", "Traveller shirt", "$350.00", "$289.00", ""],
    ["fashion.product-03", "Crewneck sweatshirt", "$220.00", "$199.00", ""],
    ["fashion.product-04", "Skinny trousers", "$300.00", "$259.00", ""],
    ["fashion.product-05", "Sleeve sweater", "$250.00", "$239.00", ""],
    ["fashion.product-06", "Pocket sweatshirt", "$200.00", "$189.00", "Hot"],
    ["fashion.product-07", "Cotton sweater", "$150.00", "$129.00", ""],
    ["fashion.product-08", "Texture regular", "$170.00", "$120.00", ""],
    ["fashion.product-09", "Sequined dress", "$190.00", "$150.00", ""],
    ["fashion.product-10", "Bermuda shorts", "$120.00", "$100.00", ""],
  ],
  promotion: {
    code: "fw205",
    message: "Take an extra 25% discount our favorite dress style. Use code:",
  },
  collection: {
    body: "Flash summer sale 70% off on selected collection for him.",
    eyebrow: "Lookbook 2023",
    heading: "New arrival collection",
    items: [
      ["fashion.collection-slider-01", "Ethnic wear", "Outfits matching"],
      ["fashion.collection-slider-02", "Dress materials", "Explore a variety"],
      ["fashion.collection-slider-03", "Western wear", "Traditional attires"],
      ["fashion.collection-slider-04", "Loungewear", "Women branded"],
      ["fashion.collection-slider-01", "Ethnic wear", "Outfits matching"],
      ["fashion.collection-slider-02", "Dress materials", "Explore a variety"],
      ["fashion.collection-slider-03", "Western wear", "Traditional attires"],
      ["fashion.collection-slider-04", "Loungewear", "Women branded"],
    ],
    options: {
      autoplayMs: 4_000,
      desktopSlides: 4,
      disableOnInteraction: false,
      keyboard: true,
      laptopSlides: 3,
      mobileSlides: 1,
      speedMs: 300,
      tabletSlides: 3,
      touch: true,
    },
  },
  brands: [
    ["fashion.brand-asos", "ASOS"],
    ["fashion.brand-chanel", "CHANEL"],
    ["fashion.brand-gucci", "GUCCI"],
    ["fashion.brand-celine", "CELINE"],
    ["fashion.brand-adidas", "adidas"],
  ],
  featuredProducts: [
    ["fashion.product-09", "Textured sweater", "$200.00", "$189.00", "New"],
    ["fashion.product-10", "Traveller shirt", "$350.00", "$289.00", ""],
    ["fashion.product-11", "Crewneck sweatshirt", "$220.00", "$199.00", ""],
    ["fashion.product-12", "Skinny trousers", "$300.00", "$259.00", ""],
    ["fashion.product-08", "Sleeve sweater", "$250.00", "$239.00", ""],
  ],
  promises: [
    "Get 20% off for your first order",
    "The fashion core collection",
    "100% secure protected payment",
    "Free shipping for orders over $130",
    "Pay with multiple credit cards",
    "Get 20% off for your first order",
    "The fashion core collection",
    "100% secure protected payment",
  ],
  promiseMarquee: {
    allowTouchMove: false,
    autoplayMs: 0,
    disableOnInteraction: false,
    keyboard: true,
    loop: true,
    speedMs: 10_000,
  },
  revealGroups: {
    brands: {
      delayMs: 0,
      durationMs: 300,
      initialTransform: "translate3d(0, -15px, 0) scale(0.8)",
      staggerMs: 100,
    },
    categories: {
      delayMs: 100,
      durationMs: 400,
      initialTransform: "perspective(1200px) translate3d(0, -15px, 0) scale(1.1) rotateX(50deg)",
      staggerMs: 200,
    },
    magazine: {
      delayMs: 300,
      durationMs: 500,
      initialTransform: "translate3d(-15px, 15px, 0)",
      staggerMs: 300,
    },
    products: {
      delayMs: 0,
      durationMs: 300,
      initialTransform: "translate3d(0, -15px, 0)",
      staggerMs: 100,
    },
    services: {
      delayMs: 200,
      durationMs: 800,
      initialTransform: "translate3d(30px, 0, 0)",
      staggerMs: 300,
    },
  },
  aboutPage: {
    milestones: [
      ["01", "Business founded"],
      ["02", "Build new office"],
      ["03", "Relocates headquarter"],
      ["04", "Revenues of millions"],
    ],
    stories: [
      ["Fashions fade style is eternal", "fashion.collection-slider-01"],
      ["I make clothes. Women make fashion", "fashion.collection-slider-02"],
      ["Something new fashion for everyone", "fashion.collection-slider-03"],
    ],
  },
  contactPage: {
    locations: [
      {
        address: "401 Broadway, 24th Floor, Orchard View, London, UK",
        city: "London",
        country: "Crafto - UK",
      },
      {
        address: "27 Eden Walk Eden Centre, Orchard, New York, USA",
        city: "New york",
        country: "Crafto - USA",
      },
    ],
  },
  faqPage: {
    categories: [
      "General",
      "Shopping information",
      "Payment information",
      "Orders and returns",
      "Ordering from crafto",
      "Help and support",
    ],
    questions: [
      "Can i order over the phone?",
      "I am having difficulty placing an order?",
      "What payment methods does accept?",
      "Can i amend my order once placed?",
      "How do i know if my order was successful?",
      "What if my order is incorrect?",
      "Can i change the delivery address?",
      "How do i return an item?",
    ],
  },
  magazinePage: [
    [
      "fashion.blog-01",
      "Den viliamson",
      "26 December 2023",
      "Elegance is not standing out, but being remembered.",
    ],
    [
      "fashion.blog-02",
      "Katie mcgrath",
      "24 December 2023",
      "Fashion is the armor to survive the reality of everyday life.",
    ],
    [
      "fashion.blog-06",
      "Rosald smith",
      "20 December 2023",
      "In order to be irreplaceable one must always be different.",
    ],
    [
      "fashion.blog-07",
      "Elizabeth taylor",
      "18 December 2023",
      "Gucci has represented design and contemporary lifestyle.",
    ],
    [
      "fashion.blog-01",
      "Rosald smith",
      "16 December 2023",
      "A designer is only as good as star who wears her clothes.",
    ],
    [
      "fashion.blog-02",
      "Elizabeth taylor",
      "14 December 2023",
      "Trying to design the perfect plan is the recipe for style.",
    ],
    [
      "fashion.blog-06",
      "Den viliamson",
      "12 December 2023",
      "Cruelty is fashion statement we can all do without.",
    ],
    [
      "fashion.blog-07",
      "Katie mcgrath",
      "12 December 2023",
      "Music and fashion have to have their own styles It's a must.",
    ],
    [
      "fashion.blog-01",
      "Elizabeth taylor",
      "10 December 2023",
      "The best accessories to add wardrobe before summer.",
    ],
    [
      "fashion.blog-02",
      "Den viliamson",
      "08 December 2023",
      "The best accessories to add wardrobe before summer.",
    ],
    [
      "fashion.blog-06",
      "Elizabeth taylor",
      "08 December 2023",
      "Fashion is architecture it is design proportions.",
    ],
    [
      "fashion.blog-07",
      "Den viliamson",
      "26 December 2023",
      "Recognizing the need is the primary condition for design.",
    ],
  ],
  magazine: [
    [
      "fashion.blog-01",
      "Den viliamson",
      "26 December 2023",
      "Elegance is not standing out, but being remembered.",
    ],
    [
      "fashion.blog-02",
      "Hugh macleod",
      "20 December 2023",
      "Fashion is the armor to survive the reality of everyday life.",
    ],
    [
      "fashion.blog-06",
      "Walton smith",
      "10 December 2023",
      "In order to be irreplaceable one must always be different.",
    ],
    [
      "fashion.blog-07",
      "Walton smith",
      "10 December 2023",
      "Gucci has represented design and contemporary lifestyle.",
    ],
  ],
  footer: {
    brand: "Lifestyle",
    brandAssetId: "fashion.logo-white",
    brandAsset2xId: "fashion.logo-white-2x",
    columns: {
      Categories: ["Men", "Women", "Accessories", "Shoes", "Dresses"],
      Information: [
        "About us",
        "Contact us",
        "Terms & conditions",
        "Shipping & delivery",
        "Privacy policy",
      ],
      "Quick links": ["My account", "Orders tracking", "Our store", "Size guide", "FAQs"],
    },
    contact: {
      email: "info@domain.com",
      phone: "123 456 7890",
      socialHeading: "Connect with us",
    },
    member: {
      body: "Join now and get 20% extra discount!",
      heading: "Become a member",
      placeholder: "Enter your email",
    },
    legal:
      "This site is protected by reCAPTCHA and the Google privacy policy and terms of service.",
    copyright: "© 2024 Crafto is Proudly Powered by ThemeZaa",
    payments: [
      "fashion.payment-01",
      "fashion.payment-02",
      "fashion.payment-03",
      "fashion.payment-04",
    ],
  },
  interactions: {
    collectionCarousel: ["previous", "next", "keyboard", "autoplay", "hover-pause", "focus-pause"],
    header: ["hover", "focus", "escape", "outside-click", "mobile-disclosure"],
    hero: ["pagination", "keyboard", "autoplay", "visibility-pause", "reduced-motion"],
    overlays: ["search", "cart", "cookie-dismiss"],
    product: ["hover", "focus", "wishlist", "quick-shop", "add-to-cart"],
  },
} as const;

export type FashionSourceContract = typeof fashionSourceContract;
