import { mkdir, readFile, readdir, unlink, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import {
  decorStorePageContracts,
  type DecorStorePageId,
} from "../app/themes/decor-store/page-contracts";

const sourceRoot = resolve(
  import.meta.dir,
  "../../../templates/Crafto - The Multipurpose HTML5 Template/html",
);
const outputDirectory = resolve(
  import.meta.dir,
  "../app/themes/decor-store/runtime/secondary-page-fragments",
);

type SecondaryPageId = Exclude<DecorStorePageId, "home">;

export const decorStoreSecondaryPageSources = Object.fromEntries(
  decorStorePageContracts
    .filter(({ id }) => id !== "home")
    .map(({ id, sourceEntry }) => [id, sourceEntry]),
) as Record<SecondaryPageId, string>;

const routeBySource = new Map(
  decorStorePageContracts.map(({ path, sourceEntry }) => [sourceEntry, path]),
);

function replaceImageTag(tag: string): string {
  const source = tag.match(/\s(?:src|data-src)=["']([^"']+)["']/i)?.[1];
  if (!source) return tag;
  const placeholder = source.match(/^https:\/\/via\.placeholder\.com\/(\d+)x(\d+)/i);
  let next = tag;
  if (placeholder) {
    const [, width, height] = placeholder;
    next = next.replaceAll(source, "__DECOR_PLACEHOLDER__");
    next = next.replace(/<img/i, `<img data-decor-placeholder="${width}x${height}"`);
  } else if (source.startsWith("images/")) {
    next = next.replaceAll(source, `__DECOR_ASSET__${source}__`);
  } else if (/^https?:\/\//i.test(source)) {
    next = next.replaceAll(source, "__DECOR_PLACEHOLDER__");
  }
  return next.replace(/\s(?:srcset|data-srcset)=["'][^"']*["']/gi, "");
}

export function sanitizeDecorStorePageFragment(source: string, pageId: SecondaryPageId): string {
  const headerEnd = source.indexOf("<!-- end header -->");
  const footerStart = source.indexOf("<!-- start footer -->");
  if (headerEnd < 0 || footerStart < 0 || footerStart <= headerEnd)
    throw new Error("Decor secondary source is missing its header/footer boundaries.");
  let fragment = source.slice(headerEnd + "<!-- end header -->".length, footerStart);
  fragment = fragment
    .replace(/<script\b[\s\S]*?<\/script>/gi, "")
    .replace(/<iframe\b[\s\S]*?<\/iframe>/gi, '<div class="decor-source-map-placeholder"></div>')
    .replace(/\sdata-anime=("[^"]*"|'[^']*')/gi, "")
    .replace(/\sdata-slider-options=("[^"]*"|'[^']*')/gi, "")
    .replace(/\sdata-map-options=("[^"]*"|'[^']*')/gi, "")
    .replace(/\son[a-z]+=("[^"]*"|'[^']*')/gi, "")
    .replace(/\saction=("[^"]*"|'[^']*')/gi, "")
    .replace(/\smethod=("[^"]*"|'[^']*')/gi, "")
    .replace(/<form\b/gi, '<div role="form" data-decor-inert-form="true"')
    .replace(/<\/form>/gi, "</div>")
    .replace(
      /<input\b([^>]*\btype=["']password["'][^>]*)>/gi,
      '<input $1 disabled aria-disabled="true">',
    )
    .replace(
      /<button\b([^>]*)\btype=["']submit["']([^>]*)>/gi,
      '<button $1 type="button" $2 disabled aria-disabled="true">',
    )
    .replace(
      /<input\b([^>]*\btype=["']submit["'][^>]*)>/gi,
      '<input $1 disabled aria-disabled="true">',
    )
    .replace(/<img\b[^>]*>/gi, replaceImageTag)
    .replace(/url\((["']?)images\/([^)'"\s]+)\1\)/gi, "url('__DECOR_ASSET__images/$2__')")
    .replace(/url\((["']?)https?:\/\/[^)]+\1\)/gi, "url('__DECOR_PLACEHOLDER__')");

  fragment = fragment.replace(
    /<a\b([^>]*?)href=["']([^"']*)["']([^>]*)>/gi,
    (_, before, href, after) => {
      if (href.startsWith("#") && href.length > 1)
        return `<a${before}href="${href}" data-decor-local-action${after}>`;
      const clean = href.split("#", 1)[0]!;
      const route = routeBySource.get(clean);
      if (route) return `<a${before}href="${route}" data-decor-store-route${after}>`;
      return `<a${before}href="#" data-decor-local-action${after}>`;
    },
  );
  let section = 0;
  return fragment
    .trim()
    .replace(/<section\b/gi, () => `<section data-decor-section="${pageId}-${++section}"`);
}

function renderFragment(fragment: string): string {
  return `// Generated by scripts/generate-decor-store-page-fragments.ts. Do not edit.\nexport default ${JSON.stringify(fragment)};\n`;
}

function renderLoaderIndex(ids: string[]): string {
  const entries = ids.map(
    (id) =>
      `  ${JSON.stringify(id)}: () => import(${JSON.stringify(`./${id}.generated`)}).then(({ default: fragment }) => fragment),`,
  );
  return `// Generated by scripts/generate-decor-store-page-fragments.ts. Do not edit.\nimport type { DecorStorePageId } from "../../page-contracts";\n\ntype SecondaryPageId = Exclude<DecorStorePageId, "home">;\n\nexport const decorStoreSecondaryPageFragmentLoaders = {\n${entries.join("\n")}\n} as const satisfies Record<SecondaryPageId, () => Promise<string>>;\n`;
}

export async function generateDecorStorePageFragments(check = false): Promise<void> {
  const fragments = Object.fromEntries(
    await Promise.all(
      Object.entries(decorStoreSecondaryPageSources).map(async ([id, file]) => [
        id,
        sanitizeDecorStorePageFragment(
          await readFile(resolve(sourceRoot, file), "utf8"),
          id as SecondaryPageId,
        ),
      ]),
    ),
  );
  const rendered = Object.fromEntries(
    Object.entries(fragments).map(([id, fragment]) => [
      `${id}.generated.ts`,
      renderFragment(fragment),
    ]),
  );
  rendered["index.generated.ts"] = renderLoaderIndex(Object.keys(fragments));
  if (check) {
    const currentFiles = (await readdir(outputDirectory).catch(() => [])).sort();
    const expectedFiles = Object.keys(rendered).sort();
    if (JSON.stringify(currentFiles) !== JSON.stringify(expectedFiles))
      throw new Error("Decor secondary fragment file inventory drifted.");
    for (const [file, content] of Object.entries(rendered)) {
      const current = await readFile(resolve(outputDirectory, file), "utf8").catch(() => "");
      if (current !== content)
        throw new Error(
          `Decor secondary fragment ${file} drifted; run generate-decor-store-page-fragments.ts.`,
        );
    }
    return;
  }
  await mkdir(outputDirectory, { recursive: true });
  const expectedFiles = new Set(Object.keys(rendered));
  for (const file of await readdir(outputDirectory)) {
    if (!expectedFiles.has(file)) await unlink(resolve(outputDirectory, file));
  }
  await Promise.all(
    Object.entries(rendered).map(([file, content]) =>
      writeFile(resolve(outputDirectory, file), content),
    ),
  );
  console.log(`Generated ${Object.keys(fragments).length} sanitized Decor page fragments.`);
}

if (import.meta.main) await generateDecorStorePageFragments(Bun.argv.includes("--check"));
