import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { pathToFileURL } from "node:url";

import {
  experienceSnapshotSchema,
  storefrontThemeDescriptorSchema,
  type StorefrontThemeDescriptor,
} from "@shoppp/contracts";
import * as z from "zod";

import { storefrontThemeCatalog } from "../app/generated/theme-catalog";

const exactHttpsOriginSchema = z
  .string()
  .url()
  .refine((value) => {
    const url = new URL(value);
    return (
      url.protocol === "https:" &&
      !url.username &&
      !url.password &&
      url.pathname === "/" &&
      !url.search &&
      !url.hash &&
      url.origin === value
    );
  }, "Preview origin must be one exact credential-free HTTPS origin.");

export const experienceBuildInputSchema = z.discriminatedUnion("environment", [
  z.object({ environment: z.literal("production") }).strict(),
  z
    .object({
      environment: z.literal("preview"),
      expectedOrigin: exactHttpsOriginSchema,
      snapshot: experienceSnapshotSchema,
      themeId: z.string().regex(/^[a-z][a-z0-9-]*$/),
    })
    .strict(),
]);

export type ExperienceBuildInput = z.infer<typeof experienceBuildInputSchema>;

export interface RenderActiveThemeOptions {
  catalog: readonly StorefrontThemeDescriptor[];
  input: ExperienceBuildInput;
  moduleAllowlist: Readonly<Record<string, string>>;
}

export interface PrepareExperienceOptions extends RenderActiveThemeOptions {
  outputPath: string;
}

const defaultModuleAllowlist = {
  "decor-store": "../themes/decor-store/registry",
  "fashion-store": "../themes/fashion-store/registry",
} as const;

function compareVersions(left: string, right: string): number {
  const leftParts = left.split(".").map(Number);
  const rightParts = right.split(".").map(Number);
  for (let index = 0; index < 3; index += 1) {
    const difference = (leftParts[index] ?? 0) - (rightParts[index] ?? 0);
    if (difference !== 0) return difference;
  }
  return 0;
}

function validatedDescriptor(
  input: Extract<ExperienceBuildInput, { environment: "preview" }>,
  catalog: readonly StorefrontThemeDescriptor[],
): StorefrontThemeDescriptor {
  const descriptors = catalog.map((entry) => storefrontThemeDescriptorSchema.parse(entry));
  const descriptor = descriptors.find(({ id }) => id === input.themeId);
  if (!descriptor) {
    throw new Error(`Theme ${input.themeId} is not present in the approved theme catalog.`);
  }
  if (
    input.snapshot.themeId !== descriptor.id ||
    input.snapshot.themeVersion !== descriptor.themeVersion ||
    input.snapshot.configurationSchemaVersion !== descriptor.configurationSchemaVersion ||
    input.snapshot.platformContractVersion !== descriptor.platformContractVersion
  ) {
    throw new Error("Preview snapshot does not match the selected theme catalog descriptor.");
  }
  if (
    compareVersions(input.snapshot.platformContractVersion, descriptor.platformCompatibility.min) <
      0 ||
    compareVersions(
      input.snapshot.platformContractVersion,
      descriptor.platformCompatibility.maxExclusive,
    ) >= 0
  ) {
    throw new Error("Selected theme is not compatible with the snapshot platform version.");
  }
  const unsupportedTemplate = input.snapshot.resolvedTemplates.find(
    ({ pageType }) => !descriptor.supportedPageTemplates.includes(pageType),
  );
  if (unsupportedTemplate) {
    throw new Error(
      `Selected theme ${descriptor.id} does not support ${unsupportedTemplate.pageType} templates.`,
    );
  }
  return descriptor;
}

function productionFallbackSource(): string {
  return `// This file is generated by apps/storefront/scripts/prepare-experience.ts.
// Production fallback intentionally imports no theme package.

import type { ExperienceSnapshot } from "@shoppp/contracts";
import type { ThemeRegistry } from "../theme-engine/registry";
import type { ThemeAssetMap } from "../theme-engine/assets";
import type { ExperienceFixtureRegistry } from "../theme-engine/view-models";
import type { ThemeRouteContract } from "../theme-engine/routes";

export const activeThemeId = "production-fallback";
export const activeExperienceSnapshot: ExperienceSnapshot | null = null;
export const activeThemeRegistry = {
  blocks: {},
  sections: {},
} as const satisfies ThemeRegistry;
export const activeThemeAssets = {} as const satisfies ThemeAssetMap;
export const activeThemeFixtures = {} as const satisfies ExperienceFixtureRegistry;
export const activeThemeRoutes = [] as const satisfies readonly ThemeRouteContract[];
export const activePreviewOrigin: string | null = null;
`;
}

export function renderActiveThemeModule({
  catalog,
  input: rawInput,
  moduleAllowlist,
}: RenderActiveThemeOptions): string {
  const input = experienceBuildInputSchema.parse(rawInput);
  if (input.environment === "production") return productionFallbackSource();

  validatedDescriptor(input, catalog);
  const modulePath = moduleAllowlist[input.themeId];
  if (!modulePath) throw new Error(`Theme ${input.themeId} is missing from the module allowlist.`);
  if (modulePath !== `../themes/${input.themeId}/registry`) {
    throw new Error(`Theme ${input.themeId} has an unsafe module allowlist path.`);
  }

  return `// This file is generated by apps/storefront/scripts/prepare-experience.ts.
// The static import below is selected before Nuxt compilation.

import type { ExperienceSnapshot } from "@shoppp/contracts";
import {
  themeAssets as selectedThemeAssets,
  themeFixtures as selectedThemeFixtures,
  themeRegistry as selectedThemeRegistry,
  themeRoutes as selectedThemeRoutes,
} from "${modulePath}";

export const activeThemeId = ${JSON.stringify(input.themeId)};
// Preserve deterministic JSON serialization for the signed snapshot payload.
// prettier-ignore
export const activeExperienceSnapshot = ${JSON.stringify(
    input.snapshot,
    null,
    2,
  )} as const satisfies ExperienceSnapshot;
export const activeThemeRegistry = selectedThemeRegistry;
export const activeThemeAssets = selectedThemeAssets;
export const activeThemeFixtures = selectedThemeFixtures;
export const activeThemeRoutes = selectedThemeRoutes;
export const activePreviewOrigin = ${JSON.stringify(input.expectedOrigin)};
`;
}

export async function prepareExperience(options: PrepareExperienceOptions): Promise<void> {
  const rendered = renderActiveThemeModule(options);
  await mkdir(dirname(resolve(options.outputPath)), { recursive: true });
  await writeFile(resolve(options.outputPath), rendered);
}

async function main(): Promise<void> {
  const root = resolve(import.meta.dir, "..");
  const inputPath = process.env.STOREFRONT_EXPERIENCE_FILE;
  const buildMode = process.env.STOREFRONT_BUILD_MODE ?? "production";
  let input: ExperienceBuildInput;
  if (inputPath) {
    if (buildMode !== "preview") {
      throw new Error("An experience build input is allowed only in preview build mode.");
    }
    input = experienceBuildInputSchema.parse(
      JSON.parse(await readFile(resolve(inputPath), "utf8")),
    );
    if (input.environment !== "preview") {
      throw new Error("The experience build file must declare preview environment.");
    }
  } else {
    if (buildMode === "preview") {
      throw new Error("Preview build mode requires STOREFRONT_EXPERIENCE_FILE.");
    }
    input = { environment: "production" };
  }
  if (input.environment === "production") {
    await rm(resolve(root, "public/theme-preview-generated"), { force: true, recursive: true });
  }
  await prepareExperience({
    catalog: storefrontThemeCatalog,
    input,
    moduleAllowlist: defaultModuleAllowlist,
    outputPath: join(root, "app/generated/active-theme.ts"),
  });
  console.log(
    input.environment === "production"
      ? "Prepared unchanged production storefront fallback."
      : `Prepared private preview for ${input.themeId} snapshot ${input.snapshot.id}.`,
  );
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? "").href) {
  await main();
}
