import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

import {
  storefrontThemeDescriptorSchema,
  type StorefrontThemeDescriptor,
} from "../packages/contracts/src/storefront-experience";
import { fashionThemeDescriptor } from "../apps/storefront/app/themes/fashion/manifest";

export interface StorefrontThemeCatalogOptions {
  descriptors: readonly StorefrontThemeDescriptor[];
  outputs: readonly string[];
}

export const STOREFRONT_THEME_MANIFEST_ALLOWLIST = [
  "apps/storefront/app/themes/fashion/manifest.ts",
] as const;

export const storefrontThemeDescriptors: readonly StorefrontThemeDescriptor[] = [
  fashionThemeDescriptor,
];

function normalizeDescriptors(
  descriptors: readonly StorefrontThemeDescriptor[],
): StorefrontThemeDescriptor[] {
  const parsed = descriptors.map((descriptor) => storefrontThemeDescriptorSchema.parse(descriptor));
  const identifiers = parsed.map(({ id }) => id);
  if (new Set(identifiers).size !== identifiers.length) {
    throw new Error("Storefront theme descriptor IDs must be unique.");
  }
  return [...parsed].sort((left, right) => left.id.localeCompare(right.id));
}

export function renderStorefrontThemeCatalog(
  descriptors: readonly StorefrontThemeDescriptor[],
): string {
  const normalized = normalizeDescriptors(descriptors);
  return [
    "// This file is generated by tools/generate-storefront-theme-catalog.ts.",
    "// Do not edit catalog entries by hand.",
    "",
    'import type { StorefrontThemeDescriptor } from "@shoppp/contracts";',
    "",
    `export const storefrontThemeCatalog = ${JSON.stringify(normalized, null, 2)} as const satisfies readonly StorefrontThemeDescriptor[];`,
    "",
  ].join("\n");
}

export async function generateStorefrontThemeCatalog({
  descriptors,
  outputs,
}: StorefrontThemeCatalogOptions): Promise<void> {
  const rendered = renderStorefrontThemeCatalog(descriptors);
  await Promise.all(outputs.map((output) => writeFile(output, rendered)));
}

export async function verifyStorefrontThemeCatalog({
  descriptors,
  outputs,
}: StorefrontThemeCatalogOptions): Promise<void> {
  const rendered = renderStorefrontThemeCatalog(descriptors);
  const contents = await Promise.all(
    outputs.map(async (output) => {
      try {
        return await readFile(output, "utf8");
      } catch {
        throw new Error(`Generated storefront theme catalog is missing: ${output}`);
      }
    }),
  );
  const staleOutput = outputs.find((_, index) => contents[index] !== rendered);
  if (staleOutput) {
    throw new Error(
      `Generated storefront theme catalog is stale: ${staleOutput}. Run the catalog generator.`,
    );
  }
}

const repositoryRoot = resolve(import.meta.dir, "..");
const repositoryOutputs = [
  resolve(repositoryRoot, "apps/api/src/generated/storefront-theme-catalog.ts"),
  resolve(repositoryRoot, "apps/storefront/app/generated/theme-catalog.ts"),
];

if (import.meta.main) {
  if (process.argv.includes("--check")) {
    await verifyStorefrontThemeCatalog({
      descriptors: storefrontThemeDescriptors,
      outputs: repositoryOutputs,
    });
    console.log("Storefront theme catalogs are current.");
  } else {
    await generateStorefrontThemeCatalog({
      descriptors: storefrontThemeDescriptors,
      outputs: repositoryOutputs,
    });
    console.log("Generated API and storefront theme catalogs.");
  }
}
